### ISSUE TITLE
App crashing when passing an empty array to adapter

### ISSUE THREAD

**Issue by edu1525** [OpenSooq/Pluto#2]
When I try to pass an empty array to my PlutoAdapter the app raises an IndexOutOfBoundsException, how can I handle this case and show a placeholder image?

**Comment by tamtom** [comment]
@edu1525  currently Pluto does not support empty array, 
my suggestion to handle this situation is to check if the array is empty before `plotu.create()` if it empty add a placeholder item.
what do you think? we are open to any suggestion for  another approach we can add to the library

**Comment by tamtom** [comment]
will close this since its user issue, please if you have any suggestion reopen it :)
