### ISSUE TITLE
how to fetch image url

### ISSUE THREAD

**Issue by fadedreams** [OpenSooq/Pluto#3]
Hi, 
I am new in android programming,
could you please guide me how to use this to load dynamic images from URL instead of using  R.drawable folder?
thanks

**Comment by JonathanNet** [comment]
Yeah I also looking for that :D

**Comment by lobothijau** [comment]
You can modify the model to have string for image url instead of int.

**Comment by MohamedHamole7** [comment]
you can fetch image url Like this @JonathanNet @colorless1 
@Override
        public void set(YourModel yourModel, int position) {
           if (yourModel.getPictureName().contains(" ")){
                Picasso.get()
                                   .load(R.drawable.empty_pic_big)
                                   .into(sliderImage);
            } else {
                Picasso.get()
                                   .load(yourModel.getPictureName())
                                   .into(sliderImage);
        }
        }

**Comment by tamtom** [comment]
@MohamedHamole7  thanks
